site_name: 客户端知识图谱

copyright: 'Copyright &copy; 2022 Ivan J. Lee.'

nav: 
    - 主页: 
      - 概述: index.md
      - 学习资料: home/ref.md
      - 关于: home/about.md
    - Android:
      - 基础:
        - Activity基础: Android/1-Basic/Activity.md
        - Service基础: Android/1-Basic/Service.md
        - BroadCastReceiver: Android/1-Basic/BroadcastReceiver.md
        - ContentProvider: Android/1-Basic/ContentProvider.md
        - 64K方法: Android/1-Basic/android-virtual-machine.md
        - Fragment与Activity通信: Android/1-Basic/fragment2activity.md
      - 性能:
        - 敬请期待: Android/2-Perf/none.md
      - 架构:
        - 敬请期待: Android/3-Arch/none.md
      - 三方框架:
        - 敬请期待: Android/4-Thirdpart/none.md
      - Framework:
        - 源码阅读计划: Android/5-Framework/Android-source-code.md
    - Java基础:
      - Java/Annotation.md
    - Kotlin基础:
      - 敬请期待: Kotlin/none.md
    - 跨平台技术:
      - 敬请期待: Cross-platform/none.md
    - CS理论基础:
      - 网络:
        - HTTP协议: CS/Internet/HTTP.md
      - 操作系统:
        - 敬请期待: CS/CS-basic/none.md
      - 计算机基础:
        - 敬请期待: CS/CS-basic/none.md
      - 算法:
        - 敬请期待: CS/Algorithm/none.md
    - 工具与工程化: 
      - 敬请期待: none.md

theme:
  language: zh
  name: 'material'
  favicon: assets/book.png
  palette:
    primary: 'teal'
    accent: 'white'
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tracking
    - navigation.top
  plugins:
    - tags: 
      enabled: true
      tags_allowed:
        - HTML5
        - JavaScript
        - CSS
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ivanjlee
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/ivanjlee
    - icon: fontawesome/solid/envelope
      link: mailto:lijundut@foxmail.com

repo_url: https://github.com/ivanjlee/frontend-roadmap
repo_name: ivanjlee/frontend-roadmap
edit_uri: ""
    
markdown_extensions:
  - def_list
  - attr_list

extra_css:
  - 'css/app.css'